name: Maven CI/CD
on:
 push:
  branches: [ master ]
 pull_request:
  branches: [ master ]

jobs:
  build_and_test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
  build-docker-image:
    name: Publish to Docker Hub
    runs-on: self-hosted
    needs: [build_and_test]
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWD }}
      - name: Build Container image
        run: sudo docker build -t ${{ secrets.DOCKER_USERNAME}}/${{ secrets.DOCKER_REPO }}:latest .
      - name: Publish Docker image
        run: sudo docker push ${{ secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPO }}
      - name: remove stop container
        run: sudo docker stop ${{ secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPO }}:latest
      - name: remove old container
        run: sudo docker rm  ${{ secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPO }}:latest
      - name: run docker container
        run: sudo docker run -it -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPO }}:latest
      - name: Docker deploy
        run: sudo sh deploy.sh
  build-docker-pull:
    name: Publish to Docker pull
    runs-on: self-hosted
    needs: [  build-docker-image ]
    steps:
     - name: docker pull and run from hub
       uses: actions/checkout@v2
       with:
        host: ec2-44-206-253-49.compute-1.amazonaws.com
        username: ubuntu
        key: ${{secrets.PEM_KEY}}
        env: GITHUB_SHA
        script: |
         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWD }}
         docker pull ${{ secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPO }}
         docker run -it -d -p 8080:8080 citagi63/github
